//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPeliculas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloPeliculasContainer : DbContext
    {
        public ModeloPeliculasContainer()
            : base("name=ModeloPeliculasContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pelicula> Peliculas { get; set; }
        public virtual DbSet<Actor> Actores { get; set; }
        public virtual DbSet<Productor> Productor { get; set; }
        public virtual DbSet<Director> DirectorSet { get; set; }
        public virtual DbSet<Comentario> Comentarios { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Premio> Premios { get; set; }
        public virtual DbSet<Certamen> Certamenes { get; set; }
        public virtual DbSet<Papel> Papeles { get; set; }
    }
}
