//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPeliculas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Premio
    {
        public string TipoPremio { get; set; }
        public int PeliculaId { get; set; }
        public int CertamenId { get; set; }
        public System.DateTime FechaEntrega { get; set; }
    
        public virtual Pelicula Pelicula { get; set; }
        public virtual Certamen Certamen { get; set; }
    }
}
